backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Bio"
        name: "bio"
        file: "content/bio.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Portrait, name: portrait, widget: image }
          - label: Exhibitions
            name: exhibitions
            widget: list
            fields:
              - { label: "Place", name: "place", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Label", name: "label", widget: "string", required: false }
          - label: Publications
            name: publications
            widget: list
            fields:
              - { label: "Medium", name: "medium", widget: "string" }
              - { label: "Date", name: "date", widget: "string" }
              - { label: "Label", name: "label", widget: "string", required: false }
              
  - name: "galleries"
    label: "Galeries"
    folder: "content/galleries"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
      - label: "Exhibitions"
        name: "exhibitions"
        widget: "list"
        fields:
          - { label: "Place", name: "place", widget: "string" }
          - { label: "Date", name: "date", widget: "string" }
          - { label: "Label", name: "label", widget: "string", required: false }
      - label: "Photos"
        name: "images"
        widget: "list"
        fields:
          - { label: "Photo", name: "src", widget: "image" }

  - name: "sales"
    label: "Sales"
    folder: "content/sales"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown"}
      - label: "Photos"
        name: "images"
        widget: "list"
        fields:
          - { label: "Photo", name: "src", widget: "image" }